Throttling:
  limit: 1000
  timeSpan: 1
  timeUnit: MINUTES
timeoutUnit: SECONDS
ssl:
  port: 443
  keyStorePassword: password
  enable: false
  keyStore: keyStore
timeout: 15
requestHandlerSortRate: 60
buffer:
  in: 100000
  files: 100000
  out: 100000
mongodb:
  dbMorphia: isites
  collectionSessions: sessions
  dbSessions: isites
  uri: mongodb://localhost:27017
limits:
  limitPostBasicSize: 16000000
  limitRequestLineSize: 8190
disableViews: false
middleware:
  loginRedirect: login
enableSecurityManager: true
enableInputThread: true
cache:
  cachedQueryMinimumAccesses: 10
  cachedAccountsMaxItems: 1000
  cachedIncludesExpiry: 3600
  cachedIncludesMaxItems: 1000
  cachedAccountIdsExpiry: 86400
  cachedBodiesMaxItems: 1000
  cachedFilesExpiry: 86400
  cachedAccountsExpiry: 1800
  cachedFilesMaxItems: 1000
  cachedAccountIdsMaxItems: 1000
  cachedSessionsMaxItems: 1000
  cachedBodiesExpiry: 3600
  cachedFilesMaxSize: 1048576
sessions:
  enableDb: true
  sessionTimeout: 86400
debug: true
webAddress: localhost
templates:
  engine: CRUSH
  applyTemplates: []
logPrefix: IncendoPasteViewer
gzip: true
Pools:
  httpsBossGroupThreads: 0
  md5Handlers: 2
  gzipHandlers: 2
  httpWorkerGroupThreads: 0
  httpBossGroupThreads: 0
  httpsWorkerGroupThreads: 0
MemoryGuard:
  runEveryMillis: 600000
verbose: true
hideIps: true
loadWebJars: false
application:
  databaseImplementation: sqlite
  main: ''
port: 1024
internalAddons:
  disabled: []
logging:
  logFormat: '&0[&c${applicationPrefix}&0]&0[&c${logPrefix}&0]&0[&c${thread}&0]&0[&c${timeStamp}&0]
    &r${message}'
autoDetectViews: false
exitOnStop: true
